### ISSUE TITLE
Ejemplo de issue

### ISSUE THREAD

**Issue by tramala** [infopublica/git-md#9]
el commit #8  esta mal

https://github.com/infopublica/git-md/blob/master/texto.md#indice

https://github.com/infopublica/git-md/blob/master/texto.md#2-estrategia-solucionismo-manipulación-y-usados

**Comment by Adrianzo** [comment]
¿ podrías explicar mejor el error @tramala ?

**Comment by martinszy** [comment]
creo que era sólo un ejemplo
